#!/bin/bash
set -eo pipefail

DOTFILES="${DOTFILES:-$HOME/.dotfiles}"
PRIVATE_DIR="${DOTFILES_PRIVATE_DIR:-$HOME/.local/share/opencode/private}"
CLAUDE_DIR="$HOME/.claude"

# Places the tracked Claude Code configuration in ~/.claude. Both files are
# written as real files rather than linked:
#
# - settings.json: Claude Code writes to it itself (/config, /model), so a
#   link would turn every in-app change into an uncommitted edit that stops
#   dotup's pull. The tracked keys are merged over the existing file instead:
#   they win on every run, and keys Claude Code added locally survive. A key
#   removed from the repo stays on machines that already have it.
# - CLAUDE.md: Cowork sessions skip a symlinked ~/.claude/CLAUDE.md, and any
#   import that points outside the session's working directory, so the file is
#   generated: the instructions shared with OpenCode, then the Claude-only
#   additions.
#
# Edits in the repo therefore reach a machine on its next dotup.

CHANGED=()

# Swap a staged file into place when its content differs from the destination.
# The rename is atomic, and replaces a symlink at the destination rather than
# writing through it.
install_staged() {
  local staged="$1" dest="$2"

  chmod 644 "$staged"
  if [[ -f "$dest" && ! -L "$dest" ]] && cmp -s "$staged" "$dest"; then
    rm -f "$staged"
    return 0
  fi
  mv "$staged" "$dest"
  CHANGED+=("$(basename "$dest")")
}

mkdir -p "$CLAUDE_DIR"

# --- CLAUDE.md ---

staged=$(mktemp "$CLAUDE_DIR/.CLAUDE.md.XXXXXX")
{
  echo "<!-- Generated by ~/.dotfiles/claude/install-config.sh from opencode/AGENTS.md"
  echo "     and claude/CLAUDE.md; edit those in the repo, not this file. -->"
  echo ""
  cat "$DOTFILES/opencode/AGENTS.md"
  echo ""
  cat "$DOTFILES/claude/CLAUDE.md"
} > "$staged"
install_staged "$staged" "$CLAUDE_DIR/CLAUDE.md"

# --- settings.json ---

# Merge order, later winning: the existing file, the tracked keys, then
# anything the optional private layer provides. jq's `*` merges objects key by
# key at every depth; any other value, arrays included, is replaced whole by
# the later file.
settings="$CLAUDE_DIR/settings.json"
sources=()
if [[ -e "$settings" ]]; then
  if ! jq empty "$settings" 2>/dev/null; then
    echo "~/.claude/settings.json is not valid JSON; left unchanged" >&2
    exit 1
  fi
  sources+=("$settings")
fi
sources+=("$DOTFILES/claude/settings.json")
if [[ -f "$PRIVATE_DIR/claude/settings.json" ]]; then
  sources+=("$PRIVATE_DIR/claude/settings.json")
fi

merged=$(jq -s 'reduce .[] as $s ({}; . * $s)' "${sources[@]}")

# Compared as data rather than text, so formatting alone never rewrites the
# file; nothing is created while there is nothing to put in it.
if [[ -e "$settings" ]]; then
  if [[ "$(jq -S . "$settings")" != "$(jq -S . <<< "$merged")" ]]; then
    staged=$(mktemp "$CLAUDE_DIR/.settings.json.XXXXXX")
    printf '%s\n' "$merged" > "$staged"
    install_staged "$staged" "$settings"
  fi
elif [[ "$merged" != "{}" ]]; then
  staged=$(mktemp "$CLAUDE_DIR/.settings.json.XXXXXX")
  printf '%s\n' "$merged" > "$staged"
  install_staged "$staged" "$settings"
fi

if [[ ${#CHANGED[@]} -gt 0 ]]; then
  echo "claude config updated (${CHANGED[*]})"
else
  echo "claude config up to date"
fi
